# This script is used to determine which genes may be affected directy or indirectly by SVs
# It requires an ini file containing additional settings and paths to input data
library(GenomicRanges)
library(ggplot2)

args <- commandArgs(trailingOnly=TRUE)
ini_file <- args[1]
output_folder <- args[2]
input_folder <- args[3]

# Load the required functions from the scripts:
source(paste(input_folder,"Scripts/Integration/SV_functions.R", sep =""))
source(paste(input_folder,"Scripts/Integration/Phenotype_functions.R", sep =""))
source(paste(input_folder,"Scripts/Integration/TAD_functions.R", sep =""))
source(paste(input_folder,"Scripts/Integration/PCHiC_functions.R", sep =""))
source(paste(input_folder,"Scripts/Integration/DHS_functions.R", sep =""))
source(paste(input_folder,"Scripts/Integration/Enhancer_functions.R", sep =""))
source(paste(input_folder,"Scripts/Integration/Expression_functions.R", sep =""))

# Create the output folder:
dir.create(output_folder)
output_file <- paste(output_folder, "Genes_SVs.txt", sep = "")

# Read the ini file:
if(file.exists(ini_file)){
  ini <- read.delim(ini_file, header = T, stringsAsFactors = F, comment.char = "#")
  project_folder <- ini[which(ini$ID == "Project_folder"), "Value"]
} else {
  stop("Could not open ini file: ", ini_file)
}

# Read the table containing the SVs:
SV_file <- paste(project_folder, ini[which(ini$ID == "SV_file"), "Value"], sep = "")
if(file.exists(SV_file)){
  raw_SVs <- read.delim(SV_file, stringsAsFactors = F)
} else {
  stop("Could not open SV_file: ", SV_file)
}

# Remove patients that are listed in Exclude_patients in the ini file:
Exclude_patients <- unlist(strsplit(x = ini[which(ini$ID == "Exclude_patients"), "Value"], split = ","))
if(ini[which(ini$ID == "Include_patients"), "Value"] != ""){
  Include_patients <- unlist(strsplit(x = ini[which(ini$ID == "Include_patients"), "Value"], split = ","))
  raw_SVs <- raw_SVs[which(raw_SVs$Patient %in% Include_patients),]
  Exclude_patients <- ""
}

# Obtain the maximum distance limit from the SVs:
distance_limit <- as.numeric(ini[which(ini$ID == "Max_distance"), "Value"])

# SV mode can be either "SVs" or "Junctions": 
SV_mode <- ini[which(ini$ID == "SV_mode"), "Value"]

# Parse the SVs to right format:
SVs <- filter_SVs(input_SVs = raw_SVs, SV_mode = SV_mode, limit = distance_limit, Patients_to_exclude = Exclude_patients)
Breakpoints <- Retrieve_breakpoints(input_SVs = SVs)

# Read the genelist. This genelist can be generated by the Generate_Genelist.R script
genelist <-  paste(project_folder,ini[which(ini$ID == "Genelist"), "Value"], sep = "")
if(file.exists(genelist)){
  print(paste("# Reading genelist: ", genelist, sep =""))
  Genes <- read.delim(genelist, stringsAsFactors = F)
} else {
  stop("Could not open genelist: ", genelist)
}

# Determine which genes are located close to the SVs:
Genes_SVs <- Overlap_Genes_SVs(Genes = Genes, SVs = SVs, Breakpoints = Breakpoints, Patients = unique(SVs$Patient), 
                               Max_Distance_from_BP = distance_limit, SV_mode = SV_mode)
#Genes_SVs <- Genes_SVs[!duplicated(Genes_SVs$Gene_ID),]
Genes_SVs2 <- Genes_SVs

# Run Phenomatch to determine the association between patient's HPO terms and genes near the SVs. This may take a while:
Phenomatch_overview <- Run_Phenomatch(phenomatch_folder = paste(project_folder,ini[which(ini$ID == "phenomatch_folder"), "Value"], sep = ""),
                                      phenomatch_raw_output_folder = paste(project_folder,ini[which(ini$ID == "phenomatch_raw_output_folder"), "Value"], sep = ""),
                                      output_folder = paste(output_folder, "Phenomatch/", sep = ""),
                                      output_filename = "Phenomatch_Overview.txt",
                                      SVs = SVs,
                                      HPO_obo_file = paste(project_folder,ini[which(ini$ID == "HPO_obo_file"), "Value"], sep = ""),
                                      HPO_genes_phenotype = paste(project_folder,ini[which(ini$ID == "HPO_genes_phenotype"), "Value"], sep = ""),
                                      HPO_patients_file = paste(project_folder,ini[which(ini$ID == "HPO_patients_file"), "Value"], sep = ""),
                                      gene_information = Genes,
                                      overwrite = ini[which(ini$ID == "Run_phenomatch"), "Value"],
                                      generate_plot = TRUE,
                                      patients = "")
  
# Add the phenomatch output to the Genes_SVs table:
Genes_SVs2 <- merge(Genes_SVs2, Phenomatch_overview[,c("Patient", "hgnc_symbol","phenoMatchScore")],
                    by = c("Patient", "hgnc_symbol"), all.x = T)

Phenomatch_hits_high <- unique(Link_HPO_Genes_to_Patients(Genes = Genes_SVs, 
                                                     HPO_file = paste(project_folder,ini[which(ini$ID == "HPO_genes_phenotype"), "Value"], sep = ""), 
                                                     Phenomatch_output_folder = paste(output_folder, "Phenomatch/", sep = ""), 
                                                     HPO_Terms_Patients = paste(project_folder, ini[which(ini$ID == "HPO_patients_file"), "Value"], sep = ""),
                                                     Phenomatch_threshold = as.numeric(ini[which(ini$ID == "Phenomatch_threshold"), "Value"])))

names(Phenomatch_hits_high)[names(Phenomatch_hits_high) == "Phenomatches"] <- "Phenomatches_high"
Phenomatch_hits_low <- unique(Link_HPO_Genes_to_Patients(Genes = Genes_SVs, 
                                                         HPO_file = paste(project_folder,ini[which(ini$ID == "HPO_genes_phenotype"), "Value"], sep = ""), 
                                                         Phenomatch_output_folder = paste(output_folder, "Phenomatch/", sep = ""), 
                                                         HPO_Terms_Patients = paste(project_folder, ini[which(ini$ID == "HPO_patients_file"), "Value"], sep = ""),
                                                         Phenomatch_threshold = 1))
names(Phenomatch_hits_low)[names(Phenomatch_hits_low) == "Phenomatches"] <- "Phenomatches_low"

Genes_SVs2 <- merge(Genes_SVs2, Phenomatch_hits_high[,c("Patient","hgnc_symbol", "Phenomatches_high", "HPO_Patient")],
                    by = c("Patient", "hgnc_symbol"), all.x = T)
Genes_SVs2 <- merge(Genes_SVs2, Phenomatch_hits_low[,c("Patient","hgnc_symbol", "Phenomatches_low")],
                    by = c("Patient", "hgnc_symbol"), all.x = T)

# Add the sexes of the patients to the Genes_SVs file
Patient_phenotypes <- read.delim( paste(project_folder,ini[which(ini$ID == "HPO_patients_file"), "Value"], sep = ""))

Genes_SVs2 <- merge(Genes_SVs2, Patient_phenotypes[!duplicated(Patient_phenotypes$Patient),c("Patient", "Sex")], by = "Patient", all.x = T)

Genes_SVs2$phenoMatchScore[is.na(Genes_SVs2$phenoMatchScore)] <- 0

# Some recently discovered ID/Autism genes do not have HPO Terms, but do have OMIM terms. More terms can be added if necessary
# First determine which patients have the following HPO terms (which will be looked for in OMIM):
HPO_Terms_Patients = read.delim( paste(project_folder,ini[which(ini$ID == "HPO_patients_file"), "Value"], sep = ""), stringsAsFactors = F)
# Name of the lists will be used as search term in OMIM terms
OMIM_terms <- list("Intellectual disability" = HPO_Terms_Patients$Patient[grep(x = HPO_Terms_Patients$HPO_ID, pattern = "HP:0001249|HP:0001263|HP:0001256|HP:0011344|HP:0000752")],
             Autis  = HPO_Terms_Patients$Patient[grep(x = HPO_Terms_Patients$HPO_ID, pattern = "HP:0000717|HP:0000729")],
             Seizure =  HPO_Terms_Patients$Patient[grep(x = HPO_Terms_Patients$HPO_ID, pattern = "HP:0000153|HP:0002123")])


# The phenotypic score is based on the pLI, RVIS, HI (HapploInsufficiency) / TS (triplosensitivity) scores and the presence in OMIM and DD2GP.
# This score is also called "disease assocation score"
Genes_SVs2$Phenotypic_score <- 0
Genes_SVs2$Phenotypic_score <- ifelse(Genes_SVs2$pLI > 0.9 & !is.na(Genes_SVs2$pLI), Genes_SVs2$Phenotypic_score + 1, Genes_SVs2$Phenotypic_score)
Genes_SVs2$Phenotypic_score <- ifelse(Genes_SVs2$RVIS < 10 & !is.na(Genes_SVs2$RVIS), Genes_SVs2$Phenotypic_score + 1, Genes_SVs2$Phenotypic_score)

Genes_SVs2$Phenotypic_score[which(Genes_SVs2$HI < 10 | Genes_SVs2$CG_HI %in% c(1,2,3) | Genes_SVs2$CG_TS %in% c(1,2,3) == TRUE)] <- 
  Genes_SVs2$Phenotypic_score[which(Genes_SVs2$HI < 10 | Genes_SVs2$CG_HI %in% c(1,2,3) | Genes_SVs2$CG_TS %in% c(1,2,3) == TRUE)]+1
Genes_SVs2$Phenotypic_score <- ifelse(!is.na(Genes_SVs2$DDG2P), Genes_SVs2$Phenotypic_score + 1, Genes_SVs2$Phenotypic_score)
Genes_SVs2$Phenotypic_score <- ifelse(!is.na(Genes_SVs2$OMIM) & Genes_SVs2$OMIM != "", Genes_SVs2$Phenotypic_score + 1, Genes_SVs2$Phenotypic_score)

summary(factor(Genes_SVs2$Phenotypic_score))

## Determine if the genes are not, weakly or strongly associated with the phenotype
# Weak drivers are only minimally associated to the phenotype and are allowed to have a recessive label (in case the recessiveness is wrongly appointed)
Genes_SVs2$Phenotype_association <- ifelse(Genes_SVs2$phenoMatchScore > 0 & 
                                             Genes_SVs2$Phenotypic_score >= 1 & 
                                             Genes_SVs2$Phenomatches_low > (Genes_SVs2$HPO_Patient*0.1), 
                                           "Weak", "None")

# Medium drivers should have a Domininant inheritance label
Genes_SVs2$Phenotype_association <- ifelse(Genes_SVs2$phenoMatchScore > 4 & 
                                             Genes_SVs2$Inheritance != "AR" & 
                                             Genes_SVs2$Inheritance != "XR" & 
                                             Genes_SVs2$Phenotypic_score >= 1 & 
                                             Genes_SVs2$Phenomatches_high > (Genes_SVs2$HPO_Patient*0.1), 
                                           "Medium", Genes_SVs2$Phenotype_association)

# X-linked recessive genes can be pathogenic in males:
Genes_SVs2$Phenotype_association <- ifelse(Genes_SVs2$phenoMatchScore > 4 & 
                                             Genes_SVs2$Inheritance == "XR" & 
                                             Genes_SVs2$Sex == "M" & 
                                             Genes_SVs2$Phenotypic_score >= 1 & 
                                             Genes_SVs2$Phenomatches_high > (Genes_SVs2$HPO_Patient*0.1), 
                                           "Medium" , Genes_SVs2$Phenotype_association)


for(OMIM_term in names(OMIM_terms)){
  #print(OMIM_term)
  Genes_SVs2$Phenotype_association <- ifelse(
    grepl(pattern = OMIM_term, x = Genes_SVs2$OMIM, ignore.case = T) == TRUE & 
      Genes_SVs2$Inheritance != "AR" & 
      grepl("XL|X-linked|Recessive", x = Genes_SVs2$OMIM, ignore.case = T) == FALSE &
      Genes_SVs2$Phenotypic_score >= 1 & 
      Genes_SVs2$Phenomatches_high > (Genes_SVs2$HPO_Patient*0.1) &
      Genes_SVs2$Patient %in% OMIM_terms[[OMIM_term]],
    "Medium", Genes_SVs2$Phenotype_association)
}

Genes_SVs2$Phenotype_association <- ifelse(Genes_SVs2$Phenotype_association == "Medium" & 
                                             (Genes_SVs2$Phenomatches_high/Genes_SVs2$HPO_Patient) >= 0.25 & 
                                             Genes_SVs2$Phenotypic_score > 2 & 
                                             Genes_SVs2$phenoMatchScore > 10, 
                                           "Strong", Genes_SVs2$Phenotype_association )

print("# Overview genes associated with Phenotype:")
summary(factor(Genes_SVs2$Phenotype_association))

## Determine disruptions of TADs, PCHiC interactions and V4C interactions
TAD_Loss <- Calculate_TAD_Loss_Gene(genes = Genes_SVs, 
                                    overwrite = TRUE, 
                                    breakpoints = Breakpoints, 
                                    TADs = paste(project_folder,ini[which(ini$ID == "TAD_file"), "Value"], sep = ""),
                                    output_folder = output_folder)

PCHiC_Disruptions <- PCHiC_disruption(Input_genes = Genes,
                                                  Genes_near_SVs = Genes_SVs,
                                                  PCHiC_data_folder = paste(project_folder,ini[which(ini$ID == "PCHiC_Folder"), "Value"], sep = ""),
                                                  cell_types = unlist(strsplit(ini[which(ini$ID == "PCHiC_Celltypes"), "Value"], split = ",")),
                                                  Input_Breakpoints = Breakpoints)

DHS_disruptions <- DHS_disruption(DHS_dataset = paste(project_folder,unlist(strsplit(ini[which(ini$ID == "DHS_file"), "Value"], split = ",")), sep = ""),
                                  output_folder = output_folder)

Genes_SVs2 <- merge(Genes_SVs2, TAD_Loss[,c("Cell_Types_TAD_Disrupted","Average_TAD_Loss", "Gene_ID")], 
                    by = "Gene_ID", all.x = T)

Genes_SVs2 <- merge(Genes_SVs2, PCHiC_Disruptions[,c("Gene_ID", "PCHiC_Interactions", "PCHiC_Disruptions")],
                    by = "Gene_ID", all.x = T)

Genes_SVs2 <- merge(Genes_SVs2, DHS_disruptions[,c("Gene_ID", "Distal_DHS_connections", "Disrupted_DHS")],
                    by = "Gene_ID", all.x = T)

# Metadata can be downloaded from: https://egg2.wustl.edu/roadmap/web_portal/meta.html
# https://docs.google.com/spreadsheets/d/1yikGx4MsO9Ei36b64yOy9Vb6oPC5IBGlFbYEt-N6gOM/edit#gid=15
encode_metadata <- read.table(paste(project_folder,ini[which(ini$ID == "Encode_metadata_file"), "Value"], sep = ""), sep = "\t", stringsAsFactors = F)
celltype_metadata <- read.table(paste(project_folder,ini[which(ini$ID == "Celltype_info_file"), "Value"], sep = ""), sep = "\t", stringsAsFactors = F, header = T)

print(paste("# Reading: ", project_folder,ini[which(ini$ID == "RNA_encode_file"), "Value"], sep = ""))
RNA_expression_data <- read.delim(paste(project_folder,ini[which(ini$ID == "RNA_encode_file"), "Value"], sep = ""))

enhancer_losses <- determine_enhancer_loss_gene(Genes_SVs = Genes_SVs2[which(Genes_SVs2$Cell_Types_TAD_Disrupted > 0),],
                                                RNA_expression_data = RNA_expression_data,
                                                input_TADs = paste(project_folder,ini[which(ini$ID == "TAD_file"), "Value"], sep = ""),
                                                folder_18_state_enhancers = paste(project_folder,ini[which(ini$ID == "ChromHMM_enhancers_18_folder"), "Value"], sep = ""),
                                                folder_15_state_enhancers = paste(project_folder,ini[which(ini$ID == "ChromHMM_enhancers_15_folder"), "Value"], sep = ""))
average_enhancer_losses <- aggregate(enhancer_losses$Enhancers_lost ~ enhancer_losses$Gene_ID, FUN = "mean")
names(average_enhancer_losses) <- c("Gene_ID", "Enhancer_loss")

Genes_SVs2 <- merge(Genes_SVs2, average_enhancer_losses[,c("Gene_ID", "Enhancer_loss")],
                    by = "Gene_ID", all.x = T)

V4C_overview <- Virtual_4C_Disruption(virtual_4c_folder = paste(project_folder,ini[which(ini$ID == "V4C_folder"), "Value"], sep = ""),
                                      output_folder = output_folder,
                                      output_filename = "V4C_Disruption_overview.txt",
                                      Genes = Genes_SVs, 
                                      re_use = ini[which(ini$ID == "V4C_reuse"), "Value"], overwrite = TRUE)
V4C_overview$Gene_ID <- row.names(V4C_overview)
Genes_SVs2 <- merge(Genes_SVs2, V4C_overview[,c("Gene_ID", "V4C_Disruption","V4C_Disruption_SD")],
                    by = "Gene_ID", all.x = T)

RNA_RPKM_files <- unlist(strsplit(ini[which(ini$ID == "RNA_RPKM_Files"), "Value"], split = ","))
RNA_DE_Folder <- ini[which(ini$ID == "RNA_DE_Folder"), "Value"]

if(!is.null(RNA_RPKM_files) & length(RNA_RPKM_files) > 0){
  RNA <- Add_RNA_RPKM_DE(RNA_RPKM_files = paste(project_folder,unlist(strsplit(ini[which(ini$ID == "RNA_RPKM_Files"), "Value"], split = ",")), sep = ""),
                         RNA_DE_Folder = paste(project_folder,ini[which(ini$ID == "RNA_DE_Folder"), "Value"], sep = ""),
                         Genes_SVs = Genes_SVs[,c("ensembl_gene_id", "Gene_ID", "Patient", "Fragment", "SV_type")])
  
  RNA2 <- Add_Trun_RNA(RNA_Truncated_DE_Folders =  paste(project_folder, unlist(strsplit(ini[which(ini$ID == "RNA_Truncated_DE_Folders"), "Value"], split = ",")), sep = ""),
					Subset_Folder = paste(project_folder,ini[which(ini$ID == "Subset_Folder"), "Value"], sep = ""),
					RNA_Output = RNA)                                     
  
  Genes_SVs2 <- merge(Genes_SVs2, RNA2[,c("Gene_ID", "RNA_RPKM","RNA_Controls_RPKM","RNA_log2FoldChange","RNA_pvalue","RNA_padj")],
                      by = "Gene_ID", all.x = T)
}


## Driver classification
## Genes are classified as T1, T2 or T3 drivers based on a combination of their phenotype association and support score

#Genes_SVs <- read.delim( "~/hpc/cog_bioinf/cuppen/project_data/Complex_svs/Results/Integration/MP/Genes_SVs.txt", stringsAsFactors = F)
Genes_SVs <- Genes_SVs2
Genes_SVs$Classification <- "No_driver"

# Change all NA's to 0's
if(!is.null(RNA_RPKM_files) & length(RNA_RPKM_files) > 0){
  Genes_SVs$RNA_pvalue[is.na(Genes_SVs$RNA_pvalue)] <- 1
}
Genes_SVs$Average_TAD_Loss[is.na(Genes_SVs$Average_TAD_Loss )] <- 0
Genes_SVs$Cell_Types_TAD_Disrupted[is.na(Genes_SVs$Cell_Types_TAD_Disrupted )] <- 0
Genes_SVs$V4C_Disruption[is.na(Genes_SVs$V4C_Disruption )] <- 0
Genes_SVs$PCHiC_Disruptions[is.na(Genes_SVs$PCHiC_Disruptions)] <- 0
Genes_SVs$PCHiC_Interactions[is.na(Genes_SVs$PCHiC_Interactions)] <- 0
Genes_SVs$phenoMatchScore[is.na(Genes_SVs$phenoMatchScore)] <- 0
Genes_SVs$Enhancer_loss[is.na(Genes_SVs$Enhancer_loss)] <- 0

Genes_SVs$Support_score <- 0
Genes_SVs$Support_score[which(Genes_SVs$Average_TAD_Loss > 10 & Genes_SVs$Cell_Types_TAD_Disrupted > 50)] <- Genes_SVs$Support_score[which(Genes_SVs$Average_TAD_Loss > 10 & Genes_SVs$Cell_Types_TAD_Disrupted > 50)] + 1
Genes_SVs$Support_score[which(Genes_SVs$V4C_Disruption > 10)] <- Genes_SVs$Support_score[which(Genes_SVs$V4C_Disruption > 10)] + 1
Genes_SVs$Support_score[which(Genes_SVs$PCHiC_Disruptions / (Genes_SVs$PCHiC_Interactions+0.1) > 0.2)] <- Genes_SVs$Support_score[which(Genes_SVs$PCHiC_Disruptions / (Genes_SVs$PCHiC_Interactions+0.1) > 0.2)] + 1
Genes_SVs$Support_score[which(Genes_SVs$Disrupted_DHS / (Genes_SVs$Disrupted_DHS+0.1) > 0.2)] <- Genes_SVs$Support_score[which(Genes_SVs$Disrupted_DHS / (Genes_SVs$Disrupted_DHS+0.1) > 0.2)] + 1
Genes_SVs$Support_score[which(Genes_SVs$Enhancer_loss > 25)] <- Genes_SVs$Support_score[which(Genes_SVs$Enhancer_loss > 25)]  + 1
Genes_SVs$Support_score[which(Genes_SVs$RNA_pvalue < 0.05)] <- Genes_SVs$Support_score[which(Genes_SVs$RNA_pvalue < 0.05)]  + 1

Genes_SVs$Support <- ifelse(Genes_SVs$Support_score > 1, "Weak", "None")
Genes_SVs$Support <- ifelse(Genes_SVs$Support_score > 4, "Strong", Genes_SVs$Support)
Genes_SVs$Support <- ifelse(Genes_SVs$SV_type %in% c("Duplication", "Insertion"), "Weak", Genes_SVs$Support )
Genes_SVs$Support <- ifelse(Genes_SVs$SV_type %in% c("Deletion", "Truncation"), "Strong", Genes_SVs$Support )

Genes_SVs$Score <- rowMeans(Genes_SVs[,c("Cell_Types_TAD_Disrupted", "V4C_Disruption", "PCHiC_Disruptions", "Disrupted_DHS", "Enhancer_loss")])

#summary(factor(Genes_SVs$Support_score))
#summary(factor(Genes_SVs$Support))
#summary(factor(Genes_SVs$Support[-which(Genes_SVs$SV_type %in% c("Deletion", "Duplication", "Truncation"))]))

Genes_SVs$Classification <- ifelse(Genes_SVs$Support != "None" & Genes_SVs$Phenotype_association %in% c("Medium", "Strong"), "T3", "No_driver")
Genes_SVs$Classification <- ifelse(Genes_SVs$Support == "Strong" & Genes_SVs$Phenotype_association == "Weak", "T3", Genes_SVs$Classification)

# Phenomatchscore are lower if only few HPO terms are reported for the patient, therefore lower threshold for T2 drivers in patients with <4 HPO terms
Genes_SVs$Classification <- ifelse(Genes_SVs$HPO_Patient <= 3 & Genes_SVs$Support == "Strong" & Genes_SVs$Phenotype_association == "Weak" & Genes_SVs$Phenotypic_score > 3,
                                   "T2", Genes_SVs$Classification)

Genes_SVs$Classification <- ifelse(Genes_SVs$Support == "Weak" & Genes_SVs$Phenotype_association == "Strong", "T2", Genes_SVs$Classification)
Genes_SVs$Classification <- ifelse(Genes_SVs$Support == "Strong" & Genes_SVs$Phenotype_association == "Medium", "T2", Genes_SVs$Classification)


Genes_SVs$Classification <- ifelse(Genes_SVs$Support == "Strong" & Genes_SVs$Phenotype_association == "Strong", "T1", Genes_SVs$Classification)

print("# Number of detected candidate drivers:")
summary(factor(Genes_SVs$Classification))
print("# Number of genes with phenotype association:")
summary(factor(Genes_SVs$Phenotype_association))
print("# Number of genes possibly affected:")
summary(factor(Genes_SVs$Support))

write.table(x = Genes_SVs, file = output_file, sep = "\t", quote = F, col.names = T, row.names = F)
for(patient in unique(Genes_SVs$Patient)){
  write.table(x = Genes_SVs[Genes_SVs$Patient == patient,], file = paste(output_folder, "Genes_SVs_",patient, ".txt", sep = ""), sep = "\t", quote = F, col.names = T, row.names = F)
}

# Generate cohort overview table
driver_summary <- patient_summary(genes_svs = Genes_SVs,
                                  phenomatch_output_folder = paste(output_folder, "Phenomatch/", sep = ""),
                                  phenomatch_threshold = 4, conclusions = c("Partially", "Largely"),
                                  conclusion_thresholds = c(0.20, 0.75))
print(driver_summary[,c(1:8)])
print(summary(factor(driver_summary$Conclusion)))
write.table(x = driver_summary, file =  paste(output_folder, "Driver_summary.txt", sep = ""), sep = "\t", quote = F, col.names = T, row.names = F)

print("SV integrator done")